### ISSUE TITLE
No structures generating

### ISSUE THREAD

**Issue by Silk-Hood** [stal111/Valhelsia-Structures#57] opened 2021-02-17 16:54 UTC
I generate a 1.16.4 world and there are no structures. I delete the chunks and change the config file names so the empty one is the server config. I relaunch the instance and I check the config file to see that the client is empty. Every time the instance is launched, the config files are resetted. /locate does not detect anything.

**Comment by danielmartin0** [comment] 2021-02-18 17:11
Post your mod list?

**Comment by Silk-Hood** [comment] 2021-02-18 22:47
Tetra
Yung's better caves
Yung's better mineshaft
Repurposed structures
Dungeon crawl
Shoulder Surfing
JEI
FPS Reducer
Oh the Biomes You'll Go
Waystones
Gravestone
Xaerox's World Map
Loot Bag
Citadel
Alex's Mobs
Quark
Chocolate

**Comment by rjulib00** [comment] 2021-03-01 12:31
looks like terraforged doesnt create the structures

**Comment by theboo** [comment] 2021-03-03 18:43
Copy the velhelsia_structures-server.toml into the default configs folder, make the changes there, then create a new world... Alternatively, in an existing world, make the changes in worldsave/serverconfigs/valhelsia_structures-server.toml

**Comment by Khytwel** [comment] 2021-05-14 23:20
This problem should be fixed in the latest version of Valhelsia Structures (1.16.5-0.1.0), the config file is now named "valhelsia_structures-common". If the problem is still present, do not hesitate to reopen an issue.

**Closed as completed by Khytwel** 2021-05-14 23:20 UTC
