### ISSUE TITLE
[Bug]: game crashed during launch

### ISSUE THREAD

**Issue by zinsser901224** [stal111/Valhelsia-Structures#159] opened 2023-03-01 19:43 UTC
### Describe the issue

game crashed during launch

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge:43.2.6
- Valhelsia Structures:1.0.1
- Valhelsia Core:

### Log

```shell
[minecraft-exported-logs-2023-03-02T03-43-07.log](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/10864727/minecraft-exported-logs-2023-03-02T03-43-07.log)
```

**Comment by KleinByte** [comment] 2023-03-02 00:11
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method valhelsia_placeDousedTorch(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/phys/BlockHitResult;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in valhelsia_structures.mixins.json:BucketItemMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap valhelsia_structures.refmap.json`

Yup I'm getting this exact same error, looks to be a compatibility issue from the new 43.2.6 forge version.

**Comment by hosheep** [comment] 2023-03-17 02:17
Mine also crashes during launch, but I'm running Forge 43.2.4.

**Comment by Vaelzan** [comment] 2023-03-17 04:43
This has been fixed, forgot to close the issue.

For those using Forge 43.2.5 or earlier, use Valhelsia Structures 1.0.1.
For those using Forge 43.2.6 or later, use Valhelsia Structures 1.0.2.

**Closed as completed by Vaelzan** 2023-03-17 04:43 UTC
Labels: Type: Bug, Status: Fixed
