### ISSUE TITLE
[Bug]: game crashes whilst initializing 

### ISSUE THREAD

**Issue by Shaemin** [stal111/Valhelsia-Structures#165] opened 2023-03-19 19:08 UTC
### **Issue**
 the game crashes whilst launching. the game launches successfully without the Valhelsia mods
### **Error message**
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: 
An unexpected critical error was encountered
Exit code: -1

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: 43.2.6 or 43.2.7 (both versions tested)
- Valhelsia Structures: 1.0.2
- Valhelsia Core: 0.5.0

### Log

```shell
https://gist.github.com/Shaemin/c8c830a4173cf3440615033d501d4508
```

**Comment by Vaelzan** [comment] 2023-03-19 19:12
OptiFine removes Minecraft code that is required for the mods to run. Please use something like Rubidium (+ Oculus for shaders) instead of OptiFine.

Duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/147

**Closed as not planned by Vaelzan** 2023-03-19 19:12 UTC
Labels: Duplicate, Type: Mod Compatibility

**Comment by Shaemin** [comment] 2023-03-20 08:39
that worked perfectly, thank you!
