### ISSUE TITLE
Fatal renderer error on server, server still boots

### ISSUE THREAD

**Issue by Suraru** [stal111/Valhelsia-Structures#76] opened 2021-05-31 21:31 UTC
Running only Valhelsia core & structures produces the following error when ran on a server:

`[main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/BlockModelRenderer for invalid dist DEDICATED_SERVER`

Full log attached
[latest.log](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/6572281/latest.log)

**Comment by Vaelzan** [comment] 2021-05-31 22:50
This is essentially a duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/73 (albeit without Mohist) - the same fix for that should resolve those errors and warnings too.

**Closed as completed** 2021-05-31 22:51 UTC
Labels: Duplicate
