### ISSUE TITLE
[Bug]: Valhelsia Core crash with Optifine HD U7

### ISSUE THREAD

**Issue by Catomax262** [stal111/Valhelsia-Structures#157] opened 2023-02-15 01:08 UTC
### Describe the issue

It crashes when i start the game.

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: 40.0.20
- Valhelsia Structures: 0.1.0
- Valhelsia Core: 0.4.0

### Log

```shell
https://gist.github.com/Catomax262/19d11d1081888f429f38447ab01448ce
```

**Comment by Vaelzan** [comment] 2023-02-15 01:09
Duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/147 - OptiFine removes code that Valhelsia Core relies on to work.

**Closed as not planned by Vaelzan** 2023-02-15 01:09 UTC
Labels: Type: Mod Compatibility

**Comment by Catomax262** [comment] 2023-02-15 02:01
What can i do?
