### ISSUE TITLE
[Bug]: game crash

### ISSUE THREAD

**Issue by venice02** [stal111/Valhelsia-Structures#154] opened 2022-12-27 13:46 UTC
### Describe the issue

...i've had issues with my homebrewn modpack, thanks to some help from the supplementaries team, we managed to pinpoint to either valhesia or valhesia core as the causes of the crash.
i was told to send my crash report here, so here it is

https://pastebin.com/wN1fTHis

### Minecraft Version

1.18.2

### Mods Version

- Forge: 
- Valhelsia Structures:
- Valhelsia Core:

### Log

```shell
https://pastebin.com/wN1fTHis
```

**Comment by Khytwel** [comment] 2022-12-27 13:49
OptiFine is not compatible with Valhelsia Core.

https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/147

**Comment by Vaelzan** [comment] 2023-01-22 18:47
Duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/147

**Closed as not planned by Vaelzan** 2023-01-22 18:47 UTC
Labels: Type: Bug
