### ISSUE TITLE
[Bug]: OptiFine is not compatible with Valhelsia Structures

### ISSUE THREAD

**Issue by Toxarcher** [stal111/Valhelsia-Structures#175] opened 2023-04-22 01:40 UTC
### Describe the issue

hello, when i put the latest version of optifine, valhesia structures, valhesia core, and valhesia furniture together, the game crashes.
i am using forge 1.19.4

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: 45.0.43
- Valhelsia Structures: 1.1.0
- Valhelsia Core: 0.5.0
- valhesia furniture: 1.1.0
- optifine: 1.19.4 HD U13

### Log

```shell
https://gist.github.com/Toxarcher/c42de19be539bfd85ae50554a5ffb2b9
```

**Comment by Vaelzan** [comment] 2023-04-22 01:53
Please read the pinned issue before reporting things. This is an issue on OptiFine's end that we can't fix, as they're removing Minecraft code that the mod relies on.

Duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/147

**Closed as not planned by Vaelzan** 2023-04-22 01:53 UTC
Labels: Duplicate
