### ISSUE TITLE
[1.18.1] Structures generate unloaded chunks or just crash the game the moment they get generated

### ISSUE THREAD

**Issue by HackX12** [stal111/Valhelsia-Structures#128] opened 2022-01-25 20:43 UTC
![image](https://user-images.githubusercontent.com/90284773/151056116-c7043380-99fd-4b39-a37b-3c57a9fc0f0d.png)
![image](https://user-images.githubusercontent.com/90284773/151056480-44b97381-371b-4c2a-a6b6-386800ac4f64.png)

[crash-2020-11-04_15.41.20-client.txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/7936995/crash-2020-11-04_15.41.20-client.txt)

**Comment by Vaelzan** [comment] 2022-01-27 10:57
I just looked at your attached crash report, and it looks like you've attached one from 2020, from Minecraft 1.16.3, and without Valhelsia Structures. I believe your issue might indeed be a duplicate of #119.

**Closed as completed by Vaelzan** 2022-01-27 10:57 UTC
Labels: Duplicate
