### ISSUE TITLE
[1.16.5-0.1.0] Pillagers spawn without any weapons as of latest update

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [stal111/Valhelsia-Structures#70] opened 2021-05-15 12:14 UTC
Forge Version: 36.1.18
Valhelsia Structures version: 0.1.0
Valhelsia Core version: 16.0.8
Latest Log: https://gist.github.com/NJL5390/24b417e9061c4f8fd42c90d6bcc2eabc

When doing a raid recently in my modpack I noticed that pillagers weren't spawning with any weapons when they spawned as part of a raid. I found that this also happens if they are spawned with a spawn egg. I have since narrowed this issue down to this mod and it does not occur without these mods installed.

This only started happening when I updated Valhelsia structures to 0.1.0 which is when this mod started to depend on Valhelsia core. 

![2021-05-15_13 07 22](https://user-images.githubusercontent.com/64381954/118360384-2cade500-b57f-11eb-9350-90d45bf0cde6.png)
![2021-05-15_13 07 31](https://user-images.githubusercontent.com/64381954/118360394-35062000-b57f-11eb-8d2b-15728e895fdf.png)
![2021-05-15_13 06 57](https://user-images.githubusercontent.com/64381954/118360405-3cc5c480-b57f-11eb-97c0-141cf77423ab.png)

**Comment by Khytwel** [comment] 2021-05-15 13:03
What is your mod list? From our side, nothing should impact the Pillagers. The Pillagers that are spawning in our structures are not connected to the Minecraft spawn system.

**Comment by Khytwel** [comment] 2021-05-15 13:12
The problem should be solved in version 0.1.1. It should be released in the next few hours.

**Comment by Khytwel** [comment] 2021-05-16 14:41
The update is now available on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures/files/3311592) and the problem is solved.

**Closed as completed by Khytwel** 2021-05-16 14:41 UTC
Labels: Status: Fixed
