### ISSUE TITLE
Game crashes when chunks are loaded in singlepayer

### ISSUE THREAD

**Issue by javijmgdev** [stal111/Valhelsia-Structures#120] opened 2022-01-20 16:14 UTC
Crash code:
https://pastebin.com/4DcQm88Q

**Comment by SigynLaufeyson** [comment] 2022-01-20 21:52
I'm getting the exact same error.  I even started a new world & the game crashes before the new world finishes loading with the error: 

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.stal111.valhelsia_structures.common.block.entity.JarBlockEntity.save(net.minecraft.nbt.CompoundTag)'
Exit Code: -1

**Comment by msameer** [comment] 2022-01-21 13:51
Same here

**Comment by emanuele246gi** [comment] 2022-01-21 16:20
Same to me

**Comment by Campbell314** [comment] 2022-01-21 20:25
I was getting the same error. Reverted Valhelsia Core mod to the valhelsia_core-1.18.1-0.3.1.jar version (vs valhelsia_core-1.18.1-0.3.2.jar), and the error isn't happening anymore.

**Comment by Vaelzan** [comment] 2022-01-22 06:27
Closing this issue, duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/119

For now, please either downgrade to Forge 39.0.44 or earlier, or wait for the next update.

**Closed as completed by Vaelzan** 2022-01-22 06:27 UTC
Labels: Duplicate
