### ISSUE TITLE
update 1.18 BlockEntity save logic

### ISSUE THREAD

**Issue by MehVahdJukaar** [stal111/Valhelsia-Structures#130] opened 2022-01-26 17:45 UTC
Just had my game crash cause of an incorrect call to the save function in JarBlockEntity
In 1.18 save logic changed and from what I've seen all "save" calls should be replaced with "saveWithoutMetadata"

**Comment by Vaelzan** [comment] 2022-01-26 17:47
https://github.com/ValhelsiaTeam/Valhelsia-Structures/commit/d9395620b053b1d3b6a6572fc7c1743bf6bd1eae :)

It's also a duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/119 - should be released fairly soon.

**Closed as completed by Vaelzan** 2022-01-26 17:47 UTC
Labels: Duplicate
