### ISSUE TITLE
[1.17.1 - 0.1.0] Error (compatibility issue with Optifine)

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [stal111/Valhelsia-Structures#109] opened 2021-11-13 16:23 UTC
> ---- Minecraft Crash Report ----
> // I let you down. Sorry :(
> 
> Time: 11/13/21, 5:23 PM
> Description: Initializing game
> 
> org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.0.7.jar:9.0.7+91+master.8569cdf] {}
> 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.0.7.jar:?] {}
> 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.0.7.jar:?] {}
> 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.0.7.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-0.9.54.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-0.9.54.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-0.9.54.jar:?] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] {}
> 	at net.minecraft.client.renderer.block.BlockRenderDispatcher.<init>(BlockRenderDispatcher.java:50) ~[client-1.17.1-20210706.113038-srg.jar%2380!:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:502) ~[client-1.17.1-20210706.113038-srg.jar%2380!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:151) ~[client-1.17.1-20210706.113038-srg.jar%2380!:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.109.jar%2322!:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}
> Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [valhelsia_structures.mixins.json:BlockModelRendererMixin] from phase [DEFAULT] in config [valhelsia_structures.mixins.json] FAILED during APPLY
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	... 29 more
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method tesselateWithAO in valhelsia_structures.mixins.json:BlockModelRendererMixin was not located in the target class net.minecraft.client.renderer.block.ModelBlockRenderer. Using refmap valhelsia_structures.refmap.json
> 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:442) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:415) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:343) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	... 29 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
> 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.0.7.jar:9.0.7+91+master.8569cdf] {}
> 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.0.7.jar:?] {}
> 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.0.7.jar:?] {}
> 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.0.7.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-0.9.54.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-0.9.54.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-0.9.54.jar:?] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] {}
> 	at net.minecraft.client.renderer.block.BlockRenderDispatcher.<init>(BlockRenderDispatcher.java:50) ~[client-1.17.1-20210706.113038-srg.jar%2380!:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:502) ~[client-1.17.1-20210706.113038-srg.jar%2380!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> -- Initialization --
> Details:
> Stacktrace:
> 	at net.minecraft.client.main.Main.main(Main.java:151) ~[client-1.17.1-20210706.113038-srg.jar%2380!:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.109.jar%2322!:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}
> 
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.17.1
> 	Minecraft Version ID: 1.17.1
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 16.0.1, Microsoft
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
> 	Memory: 2944088208 bytes (2807 MiB) / 3506438144 bytes (3344 MiB) up to 12884901888 bytes (12288 MiB)
> 	CPUs: 12
> 	Processor Vendor: AuthenticAMD
> 	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
> 	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
> 	Microarchitecture: Zen 3
> 	Frequency (GHz): 3.70
> 	Number of physical packages: 1
> 	Number of physical CPUs: 6
> 	Number of logical CPUs: 12
> 	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
> 	Graphics card #0 vendor: NVIDIA (0x10de)
> 	Graphics card #0 VRAM (MB): 4095.00
> 	Graphics card #0 deviceId: 0x1c82
> 	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
> 	Memory slot #0 capacity (MB): 8192.00
> 	Memory slot #0 clockSpeed (GHz): 2.67
> 	Memory slot #0 type: DDR4
> 	Memory slot #1 capacity (MB): 8192.00
> 	Memory slot #1 clockSpeed (GHz): 2.67
> 	Memory slot #1 type: DDR4
> 	Virtual memory max (MB): 33718.23
> 	Virtual memory used (MB): 24522.97
> 	Swap memory total (MB): 17408.00
> 	Swap memory used (MB): 1080.53
> 	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
> 	Launched Version: forge-37.0.109
> 	Backend library: LWJGL version 3.2.2 SNAPSHOT
> 	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
> 	Window size: <not initialized>
> 	GL Caps: Using framebuffer using OpenGL 3.2
> 	GL debug messages: 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'forge'
> 	Type: Client (map_client.txt)
> 	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor 
> 	OptiFine Version: OptiFine_1.17.1_HD_U_H1
> 	OptiFine Build: 20211104-012451
> 	Render Distance Chunks: 8
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: Sildurs Vibrant Shaders v1.29 Extreme.zip
> 	OpenGlVersion: 3.2.0 NVIDIA 472.12
> 	OpenGlRenderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
> 	OpenGlVendor: NVIDIA Corporation
> 	CpuCount: 12
> 	ModLauncher: 9.0.7+91+master.8569cdf
> 	ModLauncher launch target: forgeclient
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		 mixin PLUGINSERVICE 
> 		 eventbus PLUGINSERVICE 
> 		 object_holder_definalize PLUGINSERVICE 
> 		 runtime_enum_extender PLUGINSERVICE 
> 		 capability_token_subclass PLUGINSERVICE 
> 		 capability_inject_definalize PLUGINSERVICE 
> 		 accesstransformer PLUGINSERVICE 
> 		 runtimedistcleaner PLUGINSERVICE 
> 		 mixin TRANSFORMATIONSERVICE 
> 		 OptiFine TRANSFORMATIONSERVICE 
> 		 fml TRANSFORMATIONSERVICE 
> 	FML Language Providers: 
> 		minecraft@1.0
> 		javafml@null
> 	Mod List: 
> 		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
> 		morevillagers-FORGE-1.17-2.1.1.jar                |More Villagers                |morevillagers                 |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
> 		AmbientSounds_v4.0.4_mc1.17.1.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |COMMON_SET|Manifest: NOSIGNATURE
> 		MouseTweaks-forge-mc1.17.1-2.15.jar               |Mouse Tweaks                  |mousetweaks                   |2.15                |COMMON_SET|Manifest: NOSIGNATURE
> 		BiomesOPlenty-1.17.1-14.0.0.36-universal.jar      |Biomes O' Plenty              |biomesoplenty                 |1.17.1-14.0.0.36    |COMMON_SET|Manifest: NOSIGNATURE
> 		CreativeCore_v2.3.0_mc1.17.1.jar                  |CreativeCore                  |creativecore                  |2.3.0               |COMMON_SET|Manifest: NOSIGNATURE
> 		Chunky-1.2.124.jar                                |Chunky                        |chunky                        |1.2.124             |COMMON_SET|Manifest: NOSIGNATURE
> 		nether-s-exoticism-1.17.1-1.1.2.jar               |Nether's Exoticism            |nethers_exoticism             |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
> 		Fallingleaves-1.17.1-1.2.1.jar                    |Falling Leaves                |fallingleaves                 |1.2.1               |COMMON_SET|Manifest: NOSIGNATURE
> 		betterbiomeblend-1.17.1-1.2.9-forge.jar           |BetterBiomeBlend              |betterbiomeblend              |1.17.1-1.2.9-forge  |COMMON_SET|Manifest: NOSIGNATURE
> 		advancednetherite-1.9.0-1.17.1.jar                |Advanced Netherite            |advancednetherite             |1.9.0               |COMMON_SET|Manifest: NOSIGNATURE
> 		citadel-1.9.3-1.17.1.jar                          |Citadel                       |citadel                       |1.9.3               |COMMON_SET|Manifest: NOSIGNATURE
> 		alexsmobs-1.13.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.13.1              |COMMON_SET|Manifest: NOSIGNATURE
> 		NaturesCompass-1.17.1-1.9.2-forge.jar             |Nature's Compass              |naturescompass                |1.17.1-1.9.2-forge  |COMMON_SET|Manifest: NOSIGNATURE
> 		SereneSeasons-1.17.1-5.0.0.6-universal.jar        |Serene Seasons                |sereneseasons                 |1.17.1-5.0.0.6      |COMMON_SET|Manifest: NOSIGNATURE
> 		Bigger-Caves-1.17.1-v1.0.jar                      |Example Mod                   |bigger_caves                  |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
> 		architectury-2.6.35.jar                           |Architectury                  |architectury                  |2.6.35              |COMMON_SET|Manifest: NOSIGNATURE
> 		AI-Improvements-1.17.1-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |COMMON_SET|Manifest: NOSIGNATURE
> 		restored_earth-1.17.1-1.1.1.jar                   |Restored Earth                |restored_earth                |1.1.1               |COMMON_SET|Manifest: NOSIGNATURE
> 		cloth-config-5.1.40-forge.jar                     |Cloth Config v4 API           |cloth_config                  |5.1.40              |COMMON_SET|Manifest: NOSIGNATURE
> 		outvoted-1.5.0-beta.3.jar                         |Outvoted                      |outvoted                      |1.5.0-beta.3        |COMMON_SET|Manifest: NOSIGNATURE
> 		3dSkinLayers-forge-1.2.1.jar                      |3dSkinLayers                  |skinlayers3d                  |1.2.1               |COMMON_SET|Manifest: NOSIGNATURE
> 		forge-1.17.1-37.0.109-universal.jar               |Forge                         |forge                         |37.0.109            |COMMON_SET|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
> 		FastLeafDecay-26.jar                              |FastLeafDecay                 |fastleafdecay                 |26                  |COMMON_SET|Manifest: NOSIGNATURE
> 		valhelsia_core-1.17.1-0.2.0.jar                   |Valhelsia Core                |valhelsia_core                |1.17.1-0.2.0        |COMMON_SET|Manifest: NOSIGNATURE
> 		valhelsia_structures-1.17.1-0.1.0.jar             |Valhelsia Structures          |valhelsia_structures          |1.17.1-0.1.0        |COMMON_SET|Manifest: NOSIGNATURE
> 		geckolib-1.17.1-3.0.9.jar                         |GeckoLib                      |geckolib3                     |3.0.9               |COMMON_SET|Manifest: NOSIGNATURE
> 		corpse-1.17.1-1.0.4.jar                           |Corpse                        |corpse                        |1.17.1-1.0.4        |COMMON_SET|Manifest: NOSIGNATURE
> 	Crash Report UUID: ff21f6cb-1aac-4506-9f68-8157f1bceb05
> 	FML: 37.0
> 	Forge: net.minecraftforge:37.0.109

**Comment by SentientCookie** [comment] 2021-11-14 19:18
I've had this same error in my mod collection.
After a lot of testing, I discovered that OptiFine_1.17.1_HD_U_H1 was the cause of the error when also attempting to load Valhelsia Structures.
When I removed OptiFine, the game loaded up normally.
There are a few mods that are currently incompatible with 1.17.1 OptiFine and Valhelsia Structures seems to be one of them right now.

**Comment by Khytwel** [comment] 2021-11-20 15:04
Now fixed with this version: https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures/files/3531577. Thanks for your report.

**Closed as completed by Khytwel** 2021-11-20 15:04 UTC
Labels: Status: Fixed, Type: Mod Compatibility
