### ISSUE TITLE
[1.18.1] The Jars broke my server

### ISSUE THREAD

**Issue by LunafeyLazuli** [stal111/Valhelsia-Structures#124] opened 2022-01-23 01:34 UTC
valhelsia_structures-1.18.1-0.1.0.jar

[22.01 19:31:14] [Server] java.lang.NoSuchMethodError'net.minecraft.nbt.CompoundTag com.stal111.valhelsia_structures.common.block.entity.JarBlockEntity.save(net.minecraft.nbt.CompoundTag)'
[22.01 19:31:14] [Server] 	at com.stal111.valhelsia_structures.common.block.entity.JarBlockEntity.m_5995_(JarBlockEntity.java:68) ~[valhelsia_structures-1.18.1-0.1.0.jar%23214!/:1.18.1-0.1.0]
[22.01 19:31:14] [Server] 	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:153) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1125) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:785) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.server.level.ChunkMap.m_140184_(ChunkMap.java:990) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.server.level.ServerChunkCache.m_8385_(ServerChunkCache.java:448) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7185_(ServerGamePacketListenerImpl.java:850) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.m_5797_(ServerboundMovePlayerPacket.java:114) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.m_5797_(ServerboundMovePlayerPacket.java:16) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:110) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:727) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
[22.01 19:31:14] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Synthestra** [comment] 2022-01-23 02:52
The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.stal111.valhelsia_structures.common.block.entity.JarBlockEntity.save(net.minecraft.nbt.CompoundTag)'
Exit Code: -1

**Comment by Vaelzan** [comment] 2022-01-23 03:03
Closing - duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/119

**Closed as completed by Vaelzan** 2022-01-23 03:03 UTC
Labels: Duplicate
