### ISSUE TITLE
1.16 Config file blank

### ISSUE THREAD

**Issue by LadyTala** [stal111/Valhelsia-Structures#21] opened 2020-07-24 23:46 UTC
I am using 1.16 version of structures. The server side config file exists but the client side does not. I have tried to copy and paste the server config into client, and it will work and spawn a few structures, but every time I have closed the game and restarted it, it erases it again.

**Comment by Khytwel** [comment] 2020-08-13 22:09
This will be fixed for the next update which will arrive in a few days.

**Comment by Khytwel** [comment] 2020-08-14 09:30
Wait, it's not a bug. It's normal. You just need to use the .server file either for the server or singleplayer.

**Closed as completed** 2020-08-14 09:31 UTC
