### ISSUE TITLE
[1.17.1 - 0.1.0] Conflict with something (compatibility issue with Optifine)

### ISSUE THREAD

**Issue by ghost** [stal111/Valhelsia-Structures#111] opened 2021-11-16 07:17 UTC
My game crashes every time I tried to play it and I narrowed down that this mod or its core is either conflicting with a mod I have or that it is broken on mine.
Version : 1.17.1
Crash Log : https://pastebin.com/Bk0KLAjE

**Comment by Khytwel** [comment] 2021-11-16 11:32
Valhelsia Structures in 1.17 is not compatible with OptiFine.

**Comment by Khytwel** [comment] 2021-11-16 11:36
I close this issue as it is a duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/109

**Closed as completed by Khytwel** 2021-11-16 11:36 UTC
Labels: Duplicate, Type: Mod Compatibility
