### ISSUE TITLE
[Bug]: My minecraft crash after install valhelsia mods

### ISSUE THREAD

**Issue by FerrariTR** [stal111/Valhelsia-Structures#155] opened 2023-01-22 16:27 UTC
### Describe the issue

So i have a server and everything works good in the server but in my minecraft launcher after i put the valhelsia mods ( structures, furnitures and core) and it crashed, help please.

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: 43.2.3
- Valhelsia Structures: 1.19.2 - 1.0.0
- Valhelsia Core: 1.19.2-0.4.0

ps: i need help to upload the crash report, please.

**Comment by Vaelzan** [comment] 2023-01-22 16:55
Are you using OptiFine? It removes code that Valhelsia Core relies on, and is incompatible at the moment.

**Comment by FerrariTR** [comment] 2023-01-22 17:41
> Are you using OptiFine? It removes code that Valhelsia Core relies on, and is incompatible at the moment.

Yes, im using Optifine, and i want to send the crash report completely but i dont know how.. this is the message it show´s me:

The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

**Comment by Vaelzan** [comment] 2023-01-22 18:46
In that case it won't work unless you remove OptiFine. Like I said, it removes code that the mod needs.

**Comment by Vaelzan** [comment] 2023-01-22 18:46
Duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/147

**Closed as not planned by Vaelzan** 2023-01-22 18:46 UTC
Labels: Duplicate, Type: Mod Compatibility
