### ISSUE TITLE
Error code: -1 generated from Valhelsia Structures, chunks in structure not loading

### ISSUE THREAD

**Issue by StuhCuh** [stal111/Valhelsia-Structures#123] opened 2022-01-22 16:25 UTC
I am getting this error message when I load in modded minecraft with Valhelsia 1.18.1 version.

"Error: java.lang.NoSuchMethodError:

'net.minecraft.nbt.CompoundTag com.stal111.valhelsia_structures.common.block.entity.JarBlockEntity.save(net.minecraft.nbt.CompoundTag)'

Exit Code: -1"

This is what the chunks not loading look like:

![2022-01-22_11 13 00](https://user-images.githubusercontent.com/98226283/150646988-a31ae827-781b-416d-ab49-831931eb83be.png)

**Comment by Oxbower** [comment] 2022-01-22 20:18
running into the same problem in single player, game crashes after about 5 mins of playing.

version of Forge 1.18.1 39.0.58
still crashes on Forge 1.18.1 39.0.59

Time: 2022-01-22, 3:53 p.m.
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.stal111.valhelsia_structures.common.block.entity.JarBlockEntity.save(net.minecraft.nbt.CompoundTag)'

[crash-2022-01-22_15.53.50-server.txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/7919203/crash-2022-01-22_15.53.50-server.txt)

**Comment by Vaelzan** [comment] 2022-01-23 03:03
Closing - duplicate of https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/119

**Closed as completed by Vaelzan** 2022-01-23 03:03 UTC
Labels: Duplicate
