### ISSUE TITLE
[Bug]:  Crash on forge 1.19.2 - 43.1.52

### ISSUE THREAD

**Issue by zachsai** [stal111/Valhelsia-Structures#153] opened 2022-12-27 10:09 UTC
### Describe the issue

...
crash after booting game. 
Started after adding valhelsia furniture
https://gist.github.com/celsiusqc/cfa439c6ebb8f0bc923827bfa37c380c

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: 43.1.52
- Valhelsia Structures: 1.0.0
- Valhelsia Core: 0.5.0

### Log

```shell
https://gist.github.com/celsiusqc/cfa439c6ebb8f0bc923827bfa37c380c
```

**Comment by stal111** [comment] 2022-12-31 12:46
The crash was caused by a little oversight in the Every Compat mod. Update that and the issue should be fixed.

**Closed as completed by stal111** 2022-12-31 12:46 UTC
Labels: Type: Bug
