### ISSUE TITLE
Immidiate world crash on world creation

### ISSUE THREAD

**Issue by zachsai** [stal111/Valhelsia-Structures#129] opened 2022-01-26 06:12 UTC
https://pastebin.com/kEiLp94n

Forge: 39.0.55
![image](https://user-images.githubusercontent.com/63996164/151112668-1216ba66-b798-4545-9aa6-03ea9d198961.png)

**Comment by urmet** [comment] 2022-01-26 06:18
please, check pinned issues first. duplicate of #119 
![pilt](https://user-images.githubusercontent.com/1254293/151113204-feb2e432-b60c-40b7-a4f3-3a7453761419.png)

**Closed as completed** 2022-01-26 07:13 UTC
Labels: Duplicate
